version: "3"

services:
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front:/usr/src/food_professor
    command: sh -c "cd react-app && yarn start"
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "8000:3000"

volumes:
  db-data:
